const TRADITIONAL_CHINESE_REPLACEMENTS: Array<[string, string]> = [
  ['东', '東'],
  ['丝', '絲'],
  ['两', '兩'],
  ['丰', '豐'],
  ['为', '為'],
  ['丽', '麗'],
  ['乌', '烏'],
  ['亚', '亞'],
  ['伦', '倫'],
  ['伟', '偉'],
  ['伦', '倫'],
  ['体', '體'],
  ['佛', '佛'],
  ['伦', '倫'],
  ['侠', '俠'],
  ['兰', '蘭'],
  ['冈', '岡'],
  ['凯', '凱'],
  ['刘', '劉'],
  ['则', '則'],
  ['别', '別'],
  ['利', '利'],
  ['剑', '劍'],
  ['劳', '勞'],
  ['势', '勢'],
  ['华', '華'],
  ['卢', '盧'],
  ['厅', '廳'],
  ['厦', '廈'],
  ['县', '縣'],
  ['台', '臺'],
  ['号', '號'],
  ['叶', '葉'],
  ['吕', '呂'],
  ['吴', '吳'],
  ['员', '員'],
  ['启', '啟'],
  ['围', '圍'],
  ['园', '園'],
  ['国', '國'],
  ['圣', '聖'],
  ['场', '場'],
  ['坚', '堅'],
  ['坛', '壇'],
  ['坝', '壩'],
  ['岛', '島'],
  ['岭', '嶺'],
  ['峡', '峽'],
  ['岗', '崗'],
  ['岛', '島'],
  ['广', '廣'],
  ['庄', '莊'],
  ['庆', '慶'],
  ['库', '庫'],
  ['张', '張'],
  ['彻', '徹'],
  ['怀', '懷'],
  ['态', '態'],
  ['总', '總'],
  ['户', '戶'],
  ['扬', '揚'],
  ['择', '擇'],
  ['挝', '撾'],
  ['据', '據'],
  ['换', '換'],
  ['摇', '搖'],
  ['摇', '搖'],
  ['摆', '擺'],
  ['无', '無'],
  ['时', '時'],
  ['晋', '晉'],
  ['暂', '暫'],
  ['杨', '楊'],
  ['杰', '傑'],
  ['松', '松'],
  ['树', '樹'],
  ['汉', '漢'],
  ['汤', '湯'],
  ['沟', '溝'],
  ['湾', '灣'],
  ['汉', '漢'],
  ['济', '濟'],
  ['润', '潤'],
  ['滨', '濱'],
  ['灭', '滅'],
  ['灯', '燈'],
  ['灵', '靈'],
  ['点', '點'],
  ['尔', '爾'],
  ['狮', '獅'],
  ['现', '現'],
  ['环', '環'],
  ['琼', '瓊'],
  ['电', '電'],
  ['画', '畫'],
  ['盐', '鹽'],
  ['监', '監'],
  ['矿', '礦'],
  ['礼', '禮'],
  ['祯', '禎'],
  ['称', '稱'],
  ['筑', '築'],
  ['简', '簡'],
  ['类', '類'],
  ['粤', '粵'],
  ['纪', '紀'],
  ['纽', '紐'],
  ['线', '線'],
  ['维', '維'],
  ['罗', '羅'],
  ['网', '網'],
  ['纳', '納'],
  ['绍', '紹'],
  ['结', '結'],
  ['统', '統'],
  ['绝', '絕'],
  ['绿', '綠'],
  ['缅', '緬'],
  ['罗', '羅'],
  ['联', '聯'],
  ['肃', '肅'],
  ['胁', '脅'],
  ['胜', '勝'],
  ['胡', '胡'],
  ['腾', '騰'],
  ['苏', '蘇'],
  ['荣', '榮'],
  ['莲', '蓮'],
  ['营', '營'],
  ['萨', '薩'],
  ['萝', '蘿'],
  ['卫', '衛'],
  ['览', '覽'],
  ['观', '觀'],
  ['训', '訓'],
  ['设', '設'],
  ['论', '論'],
  ['贝', '貝'],
  ['贡', '貢'],
  ['费', '費'],
  ['达', '達'],
  ['迈', '邁'],
  ['远', '遠'],
  ['逊', '遜'],
  ['辽', '遼'],
  ['运', '運'],
  ['这', '這'],
  ['迪', '迪'],
  ['迹', '跡'],
  ['迈', '邁'],
  ['边', '邊'],
  ['连', '連'],
  ['迹', '跡'],
  ['铁', '鐵'],
  ['门', '門'],
  ['阳', '陽'],
  ['阴', '陰'],
  ['陈', '陳'],
  ['际', '際'],
  ['陆', '陸'],
  ['险', '險'],
  ['馆', '館'],
  ['马', '馬'],
  ['驾', '駕'],
  ['鱼', '魚'],
  ['鲁', '魯'],
  ['麦', '麥'],
  ['黄', '黃'],
  ['齐', '齊'],
  ['龙', '龍'],
]

const SIMPLIFIED_CITY_NAME_OVERRIDES: Record<string, string> = {
  albuquerque: '阿尔伯克基, N\u200BM',
  amtrak: '美铁, 美国',
  atlanta: '亚特兰大, GA',
  austin: '奥斯汀, TX',
  'california-state': '加利福尼亚州, 美国',
  boston: '波士顿, MA',
  buffalo: '布法罗, NY',
  calgary: '卡尔加里, AB',
  charlotte: '夏洛特, NC',
  nashville: '纳什维尔, TN',
  chicago: '芝加哥—基诺沙, WI',
  cincinnati: '辛辛那提, OH',
  cleveland: '克利夫兰, OH',
  dallas: '达拉斯—沃思堡, TX',
  denver: '丹佛, CO',
  detroit: '底特律, MI',
  edmonton: '埃德蒙顿, AB',
  elpaso: '埃尔帕索, TX',
  galveston: '加尔维斯顿, TX',
  algiers: '阿尔及尔, DZ',
  maracaibo: '马拉开波, VE',
  honolulu: '火奴鲁鲁, H\u200BI',
  houston: '休斯敦, TX',
  kc: '堪萨斯城, M\u200BO',
  lv: '拉斯维加斯, NV',
  lr: '小石城, AR',
  memphis: '孟菲斯, TN',
  'mexico-city': '墨西哥城, CMX',
  guadalajara: '瓜达拉哈拉, JAL',
  monterrey: '蒙特雷, NLE',
  'florida-state': '佛罗里达州, 美国',
  'san-juan': '圣胡安, PR',
  milwaukee: '密尔沃基, WI',
  twincities: '明尼阿波利斯—圣保罗, MN',
  montreal: '蒙特利尔, QC',
  morgantown: '摩根敦, WV',
  neworleans: '新奥尔良, LA',
  nyc: '纽约—新泽西—康涅狄格',
  norfolk: '诺福克, VA',
  okc: '俄克拉荷马城, OK',
  omaha: '奥马哈, NE',
  ottawa: '渥太华, ON',
  philly: '费城, PA',
  phoenix: '菲尼克斯—坦佩, AZ',
  pittsburgh: '匹兹堡, PA',
  portland: '波特兰, OR',
  slc: '盐湖城, UT',
  seattle: '西雅图—塔科马, WA',
  stl: '圣路易斯, M\u200BO',
  'toronto-waterloo': '多伦多—滑铁卢, ON',
  tucson: '图森, AZ',
  vancouver: '温哥华, BC',
  viarail: '维亚铁路, 加拿大',
  dc: '华盛顿哥伦比亚特区—巴尔的摩, DC/MD',
  barcelona: '巴塞罗那, CT',
  berlin: '柏林, BE',
  blackpool: '黑池, ENG',
  budapest: '布达佩斯, HU',
  dresden: '德累斯顿, SN',
  edinburgh: '爱丁堡, SCT',
  glasgow: '格拉斯哥, SCT',
  hamburg: '汉堡, HH',
  istanbul: '伊斯坦布尔, TR',
  karlsruhe: '卡尔斯鲁厄, BW',
  london: '伦敦, ENG',
  madrid: '马德里, MD',
  manchester: '曼彻斯特, ENG',
  munich: '慕尼黑, BY',
  nottingham: '诺丁汉, ENG',
  paris: '巴黎, FR',
  potsdam: '波茨坦, BB',
  sheffield: '谢菲尔德, ENG',
  stockholm: '斯德哥尔摩, SE',
  taw: '泰恩-威尔, ENG',
  vienna: '维也纳, AT',
  wm: '西米德兰兹, ENG',
  gba: '粤港澳大湾区, GD/HK/MO',
  pyongyang: '平壤, KP',
  seoul: '首尔, SE',
  fukuoka: '福冈, FKO',
  daegu: '大邱, DG',
  daejeon: '大田, DJ',
  busan: '釜山, BS',
  gwangju: '光州, GJ',
  singapore: '新加坡, SG',
  kaohsiung: '高雄, KHH',
  nanning: '南宁, GX',
  changchun: '\u957f\u6625, JL',
  changzhou: '\u5e38\u5dde, JS',
  dalian: '\u5927\u8fde, LN',
  fuzhou: '\u798f\u5dde, FJ',
  guiyang: '\u8d35\u9633, \u8d35\u5dde',
  harbin: '\u54c8\u5c14\u6ee8, HL',
  hohhot: '\u547c\u548c\u6d69\u7279, NM',
  jinhua: '\u91d1\u534e, ZJ',
  lanzhou: '\u5170\u5dde, GS',
  lijiang: '\u4e3d\u6c5f, YN',
  liupanshui: '\u516d\u76d8\u6c34, \u8d35\u5dde',
  luoyang: '\u6d1b\u9633, HA',
  nanchang: '\u5357\u660c, JX',
  nantong: '\u5357\u901a, JS',
  shenyang: '\u6c88\u9633, LN',
  shijiazhuang: '\u77f3\u5bb6\u5e84, HE',
  taiyuan: '\u592a\u539f, SX',
  taizhou: '\u53f0\u5dde, ZJ',
  urumqi: '\u4e4c\u9c81\u6728\u9f50, XJ',
  wenzhou: '\u6e29\u5dde, ZJ',
  wuhu: '\u829c\u6e56, AH',
  wuxi: '\u65e0\u9521, JS',
  xiamen: '\u53a6\u95e8, FJ',
  xuzhou: '\u5f90\u5dde, JS',
  taipei: '台北—新北—桃园, TPE/NWT/TAO',
  taichung: '台中, TXG',
  hochiminhcity: '胡志明市, HCM',
  hanoi: '河内, HAN',
  'thsr': '台湾高铁, TW',
  adelaide: '阿德莱德, SA',
  auckland: '奥克兰, AUK',
  canberra: '堪培拉, ACT',
  goldcoast: '黄金海岸, QLD',
  melbourne: '墨尔本, VIC',
  newcastle: '纽卡斯尔, NSW',
  perth: '珀斯, WA',
  sydney: '悉尼, NSW',
  wellington: '惠灵顿, WGN',
  yarra: '亚拉, VIC',
  'kuala-lumpur': '吉隆坡, MY',
  bangkok: '曼谷, TH',
  jakarta: '雅加达, JK',
  manila: '马尼拉, PH',
  palembang: '巨港, SS',
  'osaka-kobe': '大阪—神户, OSK-HYG',
  hiroshima: '广岛, HRS',
  nagoya: '名古屋, AIC',
  'gba-guangzhou': '广州',
  'gba-foshan': '佛山',
  'gba-dongguan': '东莞',
  'gba-shenzhen': '深圳',
  'gba-hong-kong': '香港',
  'gba-mtr-heavy-rail': '港铁（重铁）',
  'gba-mtr-light-rail': '港铁（轻铁）',
  'gba-macau': '澳门',
  'chicago-cta': '芝加哥 CTA',
  'chicago-metra': '芝加哥 Metra',
  'california-state-los-angeles': '洛杉矶',
  'california-state-bay-area': '湾区',
  'california-state-muni': '旧金山 Muni',
  'california-state-san-diego': '圣迭戈',
  'california-state-sacramento': '萨克拉门托',
  'california-state-bart': '湾区捷运 BART',
  'california-state-caltrain': 'Caltrain',
  'california-state-vta': 'VTA',
  'california-state-la-metro': '洛杉矶 Metro',
  'california-state-metrolink': 'Metrolink',
  'nyc-subway': '纽约地铁',
  'nyc-lirr': '长岛铁路',
  'nyc-mnr': '大都会北方铁路',
  'nyc-ctrail': 'CTrail',
  'nyc-mta-commuter-rail': '纽约 MTA 通勤铁路',
  'nyc-mta': '纽约 MTA',
  'nyc-path': 'PATH',
  'nyc-rapid-transit': '纽约快速轨道交通',
  'nyc-njt-light-rail': '新泽西交通轻轨',
  'nyc-njt-commuter-rail': '新泽西交通通勤铁路',
  'nyc-njt': '新泽西交通',
  'nyc-panynj': '纽约—新泽西港务局',
  'boston-subway-light-rail': '波士顿地铁与轻轨',
  'boston-commuter-rail': '波士顿通勤铁路',
  'dc-washington-dc': '华盛顿, DC',
  'dc-baltimore': '巴尔的摩, MD',
  'florida-state-miami': '迈阿密',
  'florida-state-orlando': '奥兰多',
  'florida-state-tampa': '坦帕',
  'florida-state-jacksonville': '杰克逊维尔',
  'philly-metro-patco': '费城地铁与 PATCO',
  'philly-regional-rail': '费城区域铁路',
  'toronto-waterloo-ttc': '多伦多 TTC',
  'toronto-waterloo-ttc-subway': '多伦多 TTC 地铁',
  'toronto-waterloo-ttc-streetcars': '多伦多 TTC 有轨电车',
  'toronto-waterloo-go-up': 'GO / UP Express',
  'toronto-waterloo-metrolinx': 'Metrolinx',
}

const ENGLISH_CITY_NAME_OVERRIDES: Record<string, string> = {
  gba: 'Greater Bay Area (粤港澳大湾区)',
  'gba-guangzhou': 'Guangzhou (广州)',
  'gba-foshan': 'Foshan (佛山)',
  'gba-dongguan': 'Dongguan (东莞)',
  'gba-shenzhen': 'Shenzhen (深圳)',
  'gba-hong-kong': 'Hong Kong (香港)',
  'gba-mtr-heavy-rail': 'Mass Transit Railway (Heavy Rail) — 港鐵（重鐵）',
  'gba-mtr-light-rail': 'Mass Transit Railway (Light Rail) — 港鐵（輕鐵）',
  'gba-macau': 'Macau (澳門)',
}

const normalizeSlug = (slugOrLink: string) =>
  slugOrLink.replace(/^\//, '').split(/[?#]/)[0]

const SIMPLIFIED_REGION_ABBREVIATIONS: Record<string, string> = {
  AH: '安徽',
  BJ: '北京',
  CQ: '重庆',
  FJ: '福建',
  GD: '广东',
  GS: '甘肃',
  GX: '广西',
  HA: '河南',
  HB: '湖北',
  HE: '河北',
  HI: '海南',
  HK: '香港',
  HL: '黑龙江',
  HN: '湖南',
  JL: '吉林',
  JS: '江苏',
  JX: '江西',
  LN: '辽宁',
  MO: '澳门',
  NM: '内蒙古',
  NX: '宁夏',
  SC: '四川',
  SD: '山东',
  SH: '上海',
  SX: '山西',
  TJ: '天津',
  XJ: '新疆',
  YN: '云南',
  ZJ: '浙江',
}

const TRADITIONAL_REGION_ABBREVIATIONS: Record<string, string> = {
  AH: '安徽',
  BJ: '北京',
  CQ: '重慶',
  FJ: '福建',
  GD: '廣東',
  GS: '甘肅',
  GX: '廣西',
  HA: '河南',
  HB: '湖北',
  HE: '河北',
  HI: '海南',
  HK: '香港',
  HL: '黑龍江',
  HN: '湖南',
  JL: '吉林',
  JS: '江蘇',
  JX: '江西',
  LN: '遼寧',
  MO: '澳門',
  NM: '內蒙古',
  NX: '寧夏',
  SC: '四川',
  SD: '山東',
  SH: '上海',
  SX: '山西',
  TJ: '天津',
  XJ: '新疆',
  YN: '雲南',
  ZJ: '浙江',
}

const localizeRegionAbbreviationChunk = (value: string, language: string) => {
  const map =
    language === 'zh-TW'
      ? TRADITIONAL_REGION_ABBREVIATIONS
      : SIMPLIFIED_REGION_ABBREVIATIONS

  return value.replace(/\b([A-Z]{2,3}(?:\/[A-Z]{2,3})+|[A-Z]{2,3})\b/g, (match) => {
    const parts = match.split('/')
    const localizedParts = parts.map((part) => map[part] ?? null)
    if (localizedParts.some((part) => part === null)) {
      return match
    }
    return localizedParts.join('/')
  })
}

const normalizeChineseMunicipalityName = (value: string, language: string) => {
  const municipalities =
    language === 'zh-TW'
      ? ['北京', '天津', '上海', '重慶']
      : ['北京', '天津', '上海', '重庆']

  for (const municipality of municipalities) {
    if (value === `${municipality}, ${municipality}`) {
      return `${municipality}市`
    }
  }

  return value
}

const extractEmbeddedCjkName = (
  name: string,
  language: string,
): string | null => {
  const normalized = name.replace(/â€“|â€”/g, '—').replace(/–|—/g, '—')
  const match = normalized.match(/\(([^()]*[\u3400-\u9FFF][^()]*)\)/)
  if (!match || typeof match.index !== 'number') {
    return null
  }
  const suffix = normalized.slice(match.index + match[0].length)
  const embedded = match[1].trim()
  const combined = localizeRegionAbbreviationChunk(`${embedded}${suffix}`.trim(), language)
  if (language === 'zh-TW') {
    return normalizeChineseMunicipalityName(toTraditionalChinese(combined), language)
  }
  return normalizeChineseMunicipalityName(combined, language)
}

const toTraditionalChinese = (value: string) =>
  TRADITIONAL_CHINESE_REPLACEMENTS.reduce(
    (current, [from, to]) => current.replaceAll(from, to),
    value,
  )

export const formatLocalizedCityName = (
  name: string,
  slugOrLink: string,
  language?: string | null,
) => {
  const normalized = normalizeSlug(slugOrLink)
  const lastSegment = normalized.split('/').filter(Boolean).pop() ?? normalized

  if (language === 'en') {
    return (
      ENGLISH_CITY_NAME_OVERRIDES[normalized] ??
      ENGLISH_CITY_NAME_OVERRIDES[lastSegment] ??
      name
    )
  }

  if (language !== 'zh-CN' && language !== 'zh-TW') {
    return name
  }
  const explicit =
    SIMPLIFIED_CITY_NAME_OVERRIDES[normalized] ??
    SIMPLIFIED_CITY_NAME_OVERRIDES[lastSegment]

  if (explicit) {
    const localized = localizeRegionAbbreviationChunk(explicit, language)
    if (language === 'zh-TW') {
      return normalizeChineseMunicipalityName(toTraditionalChinese(localized), language)
    }
    return normalizeChineseMunicipalityName(localized, language)
  }

  const embedded = extractEmbeddedCjkName(name, language)
  if (embedded) {
    return embedded
  }

  return name
}
