-- Drop the legacy Automation* system (tables, foreign keys, enums).
-- Replaced by the Research* models. Data is intentionally discarded.

ALTER TABLE "AutomationAgentActionRequest" DROP CONSTRAINT "AutomationAgentActionRequest_claimId_fkey";
ALTER TABLE "AutomationAgentActionRequest" DROP CONSTRAINT "AutomationAgentActionRequest_messageId_fkey";
ALTER TABLE "AutomationAgentActionRequest" DROP CONSTRAINT "AutomationAgentActionRequest_runRequestId_fkey";
ALTER TABLE "AutomationAgentActionRequest" DROP CONSTRAINT "AutomationAgentActionRequest_sessionId_fkey";
ALTER TABLE "AutomationAgentEvent" DROP CONSTRAINT "AutomationAgentEvent_claimId_fkey";
ALTER TABLE "AutomationAgentEvent" DROP CONSTRAINT "AutomationAgentEvent_messageId_fkey";
ALTER TABLE "AutomationAgentEvent" DROP CONSTRAINT "AutomationAgentEvent_runRequestId_fkey";
ALTER TABLE "AutomationAgentEvent" DROP CONSTRAINT "AutomationAgentEvent_sessionId_fkey";
ALTER TABLE "AutomationAgentMessage" DROP CONSTRAINT "AutomationAgentMessage_parentMessageId_fkey";
ALTER TABLE "AutomationAgentMessage" DROP CONSTRAINT "AutomationAgentMessage_revisionOfMessageId_fkey";
ALTER TABLE "AutomationAgentMessage" DROP CONSTRAINT "AutomationAgentMessage_sessionId_fkey";
ALTER TABLE "AutomationAgentOutcome" DROP CONSTRAINT "AutomationAgentOutcome_claimId_fkey";
ALTER TABLE "AutomationAgentOutcome" DROP CONSTRAINT "AutomationAgentOutcome_messageId_fkey";
ALTER TABLE "AutomationAgentOutcome" DROP CONSTRAINT "AutomationAgentOutcome_runRequestId_fkey";
ALTER TABLE "AutomationAgentOutcome" DROP CONSTRAINT "AutomationAgentOutcome_sessionId_fkey";
ALTER TABLE "AutomationArtifact" DROP CONSTRAINT "AutomationArtifact_runId_fkey";
ALTER TABLE "AutomationArtifactCitation" DROP CONSTRAINT "AutomationArtifactCitation_artifactId_fkey";
ALTER TABLE "AutomationArtifactCitation" DROP CONSTRAINT "AutomationArtifactCitation_claimId_fkey";
ALTER TABLE "AutomationArtifactCitation" DROP CONSTRAINT "AutomationArtifactCitation_researchTaskId_fkey";
ALTER TABLE "AutomationCandidate" DROP CONSTRAINT "AutomationCandidate_runId_fkey";
ALTER TABLE "AutomationClaim" DROP CONSTRAINT "AutomationClaim_candidateId_fkey";
ALTER TABLE "AutomationClaim" DROP CONSTRAINT "AutomationClaim_runId_fkey";
ALTER TABLE "AutomationClaimArtifact" DROP CONSTRAINT "AutomationClaimArtifact_artifactId_fkey";
ALTER TABLE "AutomationClaimArtifact" DROP CONSTRAINT "AutomationClaimArtifact_claimId_fkey";
ALTER TABLE "AutomationDecision" DROP CONSTRAINT "AutomationDecision_candidateId_fkey";
ALTER TABLE "AutomationEvidenceEdge" DROP CONSTRAINT "AutomationEvidenceEdge_claimId_fkey";
ALTER TABLE "AutomationEvidenceEdge" DROP CONSTRAINT "AutomationEvidenceEdge_fromNodeId_fkey";
ALTER TABLE "AutomationEvidenceEdge" DROP CONSTRAINT "AutomationEvidenceEdge_toNodeId_fkey";
ALTER TABLE "AutomationEvidenceNode" DROP CONSTRAINT "AutomationEvidenceNode_claimId_fkey";
ALTER TABLE "AutomationEvidenceNode" DROP CONSTRAINT "AutomationEvidenceNode_researchTaskId_fkey";
ALTER TABLE "AutomationPolicyDecision" DROP CONSTRAINT "AutomationPolicyDecision_claimId_fkey";
ALTER TABLE "AutomationResearchRun" DROP CONSTRAINT "AutomationResearchRun_claimId_fkey";
ALTER TABLE "AutomationResearchRun" DROP CONSTRAINT "AutomationResearchRun_parentRunId_fkey";
ALTER TABLE "AutomationResearchTask" DROP CONSTRAINT "AutomationResearchTask_claimId_fkey";
ALTER TABLE "AutomationResearchTask" DROP CONSTRAINT "AutomationResearchTask_researchRunId_fkey";
ALTER TABLE "AutomationResearchTaskArtifact" DROP CONSTRAINT "AutomationResearchTaskArtifact_artifactId_fkey";
ALTER TABLE "AutomationResearchTaskArtifact" DROP CONSTRAINT "AutomationResearchTaskArtifact_researchTaskId_fkey";
ALTER TABLE "AutomationRunRequest" DROP CONSTRAINT "AutomationRunRequest_messageId_fkey";
ALTER TABLE "AutomationRunRequest" DROP CONSTRAINT "AutomationRunRequest_sessionId_fkey";
ALTER TABLE "AutomationSource" DROP CONSTRAINT "AutomationSource_candidateId_fkey";
ALTER TABLE "AutomationVerification" DROP CONSTRAINT "AutomationVerification_claimId_fkey";
DROP TABLE "AutomationAgentActionRequest";
DROP TABLE "AutomationAgentEvent";
DROP TABLE "AutomationAgentMessage";
DROP TABLE "AutomationAgentOutcome";
DROP TABLE "AutomationAgentSession";
DROP TABLE "AutomationArtifact";
DROP TABLE "AutomationArtifactCitation";
DROP TABLE "AutomationCandidate";
DROP TABLE "AutomationClaim";
DROP TABLE "AutomationClaimArtifact";
DROP TABLE "AutomationDecision";
DROP TABLE "AutomationEvalRun";
DROP TABLE "AutomationEvidenceEdge";
DROP TABLE "AutomationEvidenceNode";
DROP TABLE "AutomationPolicyDecision";
DROP TABLE "AutomationPolicyMetric";
DROP TABLE "AutomationResearchMemory";
DROP TABLE "AutomationResearchRun";
DROP TABLE "AutomationResearchTask";
DROP TABLE "AutomationResearchTaskArtifact";
DROP TABLE "AutomationRun";
DROP TABLE "AutomationRunRequest";
DROP TABLE "AutomationSource";
DROP TABLE "AutomationSourceDomain";
DROP TABLE "AutomationVerification";
DROP TYPE "AutomationAgentActionSafety";
DROP TYPE "AutomationAgentActionStatus";
DROP TYPE "AutomationAgentEventType";
DROP TYPE "AutomationAgentMessageRole";
DROP TYPE "AutomationAgentMessageStatus";
DROP TYPE "AutomationAgentOutcomeType";
DROP TYPE "AutomationAgentSessionType";
DROP TYPE "AutomationApplyPolicy";
DROP TYPE "AutomationArtifactType";
DROP TYPE "AutomationCandidateType";
DROP TYPE "AutomationCitationLocatorType";
DROP TYPE "AutomationClaimStatus";
DROP TYPE "AutomationDecisionStatus";
DROP TYPE "AutomationEvidenceEdgeType";
DROP TYPE "AutomationEvidenceNodeType";
DROP TYPE "AutomationLane";
DROP TYPE "AutomationMetricScope";
DROP TYPE "AutomationResearchMemoryKind";
DROP TYPE "AutomationResearchRunStatus";
DROP TYPE "AutomationResearchTaskStatus";
DROP TYPE "AutomationResearchTaskType";
DROP TYPE "AutomationRunRequestMode";
DROP TYPE "AutomationRunRequestStatus";
DROP TYPE "AutomationRunStatus";
DROP TYPE "AutomationSourceTier";
